## Made by: Angela Franco
## 1) makeCacheMatrix receives a matrix as a parameter and creates a set of functions that allow to 
## set and get a matrix, and also set and get the inverse of the matrix.Returns an object that can
## use all the 4 inner functions
## 2) cacheSolve receives the object generated by makeCacheMatrix and checks whether a matrix inverse
## was calculated already or not, if it was not calculated then get the data from the makeCacheMatrix
## object and then solves it. Otherwise, it returns the cached inverse of the matrix.

## Write a short comment describing this function

makeCacheMatrix <- function(x = matrix()) {
  i <- NULL
  set <- function (y)
  {
    x <<- y
    i <<- NULL
  }
  get <- function () x
  setinv <- function (inverse) i <<- inverse
  getinv <- function () i
  list(set = set, get = get, 
       setinv = setinv, getinv = getinv)
}


## Write a short comment describing this function

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  i <- x$getinv()
  if(!is.null(i))
  {
    message("getting cached inverse matrix")
    return(i)
  }
  data <- x$get()
  i <- solve(data, ...)
  x$setinv(i)
  i
}
